### ISSUE TITLE
手部姿态的训练代码可以公开吗？

### ISSUE THREAD

**Issue by Amanda-Barbara** [FeiGeChuanShu/ncnn_nanodet_hand#1]

**Comment by FeiGeChuanShu** [comment]
coming soon @Amanda-Barbara

**Comment by Amanda-Barbara** [comment]
@FeiGeChuanShu 多谢哈，期待中……

**Comment by salviatia** [comment]
能提供一下模型的代码吗？

**Comment by FeiGeChuanShu** [comment]
> 能提供一下模型的代码吗？

就是仿照pfld改的，模型文件已经给出了，用netron打开模仿网络结构就能自己复现，上传模型代码还要等等

**Comment by salviatia** [comment]
@FeiGeChuanShu 谢谢🙏

**Comment by 205418367** [comment]
能不能提供onnx模型？

**Comment by FeiGeChuanShu** [comment]
@205418367  your email

**Comment by salviatia** [comment]
> > 能提供一下模型的代码吗？
> 
> 就是仿照pfld改的，模型文件已经给出了，用netron打开模仿网络结构就能自己复现，上传模型代码还要等等

checkpoint能提供嘛？
