### ISSUE TITLE
如何判断左右手？

### ISSUE THREAD

**Issue by duoduo888999** [FeiGeChuanShu/ncnn_nanodet_hand#12]
代码中没有体现左右手的判断。
请问是通过大拇指的位置来判断左右手的吗

**Comment by FeiGeChuanShu** [comment]
> 代码中没有体现左右手的判断。 请问是通过大拇指的位置来判断左右手的吗

https://github.com/FeiGeChuanShu/ncnn_nanodet_hand/blob/main/ncnn-yolox-hand/app/src/main/jni/landmark.cpp#L85

https://github.com/FeiGeChuanShu/ncnn_nanodet_hand/blob/main/ncnn-android-nanodet/app/src/main/jni/nanodet.cpp#L470 通过这个score判断 是个二分类 具体是哪个手自己测一下吧

**Comment by duoduo888999** [comment]
谢谢！已判断出左右手
