### ISSUE TITLE
implement new handpose model?

### ISSUE THREAD

**Issue by GeorvityLabs** [FeiGeChuanShu/ncnn_nanodet_hand#7]

**Comment by GeorvityLabs** [comment]
model link : https://maven.google.com/web/index.html?#com.google.mediapipe:hands:0.8.9-alpha-1
Documentation : https://blog.tensorflow.org/2021/11/3D-handpose.html

**Comment by FeiGeChuanShu** [comment]
@GeorvityLabs coming soon maybe tonight

**Comment by GeorvityLabs** [comment]
> @GeorvityLabs coming soon maybe tonight

awesome ,hope you will also include Finger Count this time if possible. To identify how many fingers are open and in which hand (left or right).

**Comment by FeiGeChuanShu** [comment]
@GeorvityLabs the new model has updated

**Comment by GeorvityLabs** [comment]
> @GeorvityLabs the new model has updated

awesome. could we expect , finger open/close count function as a new feature?

**Comment by GeorvityLabs** [comment]
A function to count how many fingers are open or closed in a hand.
