### ISSUE TITLE
误检有点高

### ISSUE THREAD

**Issue by imistyrain** [FeiGeChuanShu/ncnn_nanodet_hand#8]
经常把脸误认为手

**Comment by FeiGeChuanShu** [comment]
@imistyrain 用的nanodet还是yolox，训练数据太少了没办法，yolox会好一点，可以自己训练一个hand detect替换的，比如yolov5-lite、yolov5n6.0、yolox啥的

**Comment by willard-yuan** [comment]
看demo，感觉检测速度还有待提高，至少要到20多fps吧

**Comment by imistyrain** [comment]
> 看demo，感觉检测速度还有待提高，至少要到20多fps吧

用高通845 有28FPS

**Comment by 205418367** [comment]
请问你的检测算法会把检测到的目标（手）进行矫正么？比如，手掌朝下检测后返回朝上的手掌。

**Comment by 205418367** [comment]
没有考虑用 mediapipe 上的 hand detect 算法么？

**Comment by FeiGeChuanShu** [comment]
> 请问你的检测算法会把检测到的目标（手）进行矫正么？比如，手掌朝下检测后返回朝上的手掌。

目前没有

**Comment by FeiGeChuanShu** [comment]
> 没有考虑用 mediapipe 上的 hand detect 算法么？

如果有时间会看看

**Comment by FeiGeChuanShu** [comment]
> 请问你的检测算法会把检测到的目标（手）进行矫正么？比如，手掌朝下检测后返回朝上的手掌。

https://github.com/FeiGeChuanShu/ncnn-Android-mediapipe_hand 搞了个demo 可以看看，用的mediapipe的palm detect和hand landmark
