### ISSUE TITLE
hand pose算法哪个好些？有做过专业测试的么？

### ISSUE THREAD

**Issue by 205418367** [FeiGeChuanShu/ncnn_nanodet_hand#9]
1.pfld
2.mediapipe hand
哪个好些？我用的是mediapipe hand，如果有更好的关键点算法我会用tensorrt复现一下，谢谢！

**Comment by FeiGeChuanShu** [comment]
> 1.pfld 2.mediapipe hand 哪个好些？我用的是mediapipe hand，如果有更好的关键点算法我会用tensorrt复现一下，谢谢！

2好一些，毕竟是Google出品；1是自己用开源数据集训的，碍于没有好的数据集，未进行下去

**Comment by 205418367** [comment]
了解了！
